apiVersion: v1
kind: Service
metadata:
  name: agent-server-{{ .Values.env }}
spec:
  type: ClusterIP
  ports:
    - name: server
      port: {{ .Values.service.ports.server.port }}
      protocol: TCP
      targetPort: {{ .Values.service.ports.server.targetPort }}
  selector:
    app: agent-server
    env: {{ .Values.env }}
