apiVersion: v1
kind: PersistentVolume
metadata:
  name: agent-db-{{ .Values.env }}
spec:
  capacity:
    storage: {{ .Values.ebs_volume.size }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  reclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: {{ .Values.ebs_volume.id }}
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-db-{{ .Values.env }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.ebs_volume.size }}
  storageClassName: ""
  volumeName: agent-db-{{ .Values.env }}
